---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./kube-vip/application.yaml
  - ./local-path-provisioner/application.yaml
  - ./metrics-server/application.yaml
  - ./reloader/application.yaml
