---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
helmCharts:
  - name: app-template
    releaseName: echo-server
    namespace: default
    repo: https://bjw-s.github.io/helm-charts/
    version: 2.6.0
    valuesFile: values.yaml
