---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
helmCharts:
  - name: local-path-provisioner
    releaseName: local-path-provisioner
    namespace: kube-system
    repo: https://hajimari.io
    version: 2.0.2
    valuesFile: values.yaml
