helperImage:
  repository: public.ecr.aws/docker/library/busybox
  tag: latest
storageClass:
  defaultClass: false
nodePathMap:
  - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
    paths: ["/var/lib/rancher/k3s/storage"]
configmap:
  setup: |-
    #!/bin/sh
    while getopts "m:s:p:" opt
    do
        case $opt in
            p)
            absolutePath=$OPTARG
            ;;
            s)
            sizeInBytes=$OPTARG
            ;;
            m)
            volMode=$OPTARG
            ;;
        esac
    done
    mkdir -m 0777 -p $${absolutePath}
    chmod 701 $${absolutePath}/..
  teardown: |-
    #!/bin/sh
    while getopts "m:s:p:" opt
    do
        case $opt in
            p)
            absolutePath=$OPTARG
            ;;
            s)
            sizeInBytes=$OPTARG
            ;;
            m)
            volMode=$OPTARG
            ;;
        esac
    done
    rm -rf $${absolutePath}
