---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/coolguy1771/argo-cluster-template.git
    targetRevision: HEAD
    path: kubernetes/apps/networking/metallb/app
  destination:
    server: https://kubernetes.default.svc
    namespace: networking
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/coolguy1771/argo-cluster-template.git
    targetRevision: HEAD
    path: kubernetes/apps/networking/metallb/config
  destination:
    server: https://kubernetes.default.svc
    namespace: networking
