---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
helmCharts:
  - name: metrics-server
    releaseName: metrics-server
    namespace: kube-system
    repo: https://kubernetes-sigs.github.io/metrics-server
    version: 3.12.1
    valuesFile: values.yaml
