fullnameOverride: external-dns
provider: cloudflare
env:
  - name: CF_API_EMAIL
    valueFrom:
      secretKeyRef:
        name: external-dns-secret
        key: email
  - name: CF_API_KEY
    valueFrom:
      secretKeyRef:
        name: external-dns-secret
        key: api-key
extraArgs:
  - --annotation-filter=external-dns.alpha.kubernetes.io/target
  - --cloudflare-proxied
  - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
  - --crd-source-kind=DNSEndpoint
policy: sync
sources: ["crd", "ingress"]
txtPrefix: k8s.
txtOwnerId: default
domainFilters: ["${SECRET_DOMAIN}"]
serviceMonitor:
  enabled: true
podAnnotations:
  secret.reloader.stakater.com/reload: external-dns-secret
