interval: 2m
# logLevel: debug
provider: cloudflare
env:
  - name: CF_API_EMAIL
    valueFrom:
      secretKeyRef:
        name: external-dns-secret
        key: email
  - name: CF_API_KEY
    valueFrom:
      secretKeyRef:
        name: external-dns-secret
        key: api-key
extraArgs:
  - --cloudflare-proxied
  - --annotation-filter=external-dns.home.arpa/enabled in (true)
policy: sync
sources: ["ingress"]
txtPrefix: k8s.
txtOwnerId: default
domainFilters: ["${SECRET_DOMAIN}"]
serviceMonitor:
  enabled: true
podAnnotations:
  secret.reloader.stakater.com/reload: external-dns-secret
