---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/coolguy1771/argo-cluster-template.git
    targetRevision: HEAD
    path: kubernetes/apps/cert-manager/cert-manager/app
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuers
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/coolguy1771/argo-cluster-template.git
    targetRevision: HEAD
    path: kubernetes/apps/cert-manager/cert-manager/issuers
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
