---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hajimari
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/coolguy1771/argo-cluster-template.git
    targetRevision: HEAD
    path: kubernetes/apps/default/hajimari/app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
