---
name: "Link Check"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  link-check:
    name: Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Restore lychee cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Link Checker
        uses: lycheeverse/lychee-action@c053181aa0c3d17606addfe97a9075a32723548a # v1.9.3
        id: lychee
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          args: >
            --cache
            --max-cache-age 1d
            --verbose
            --no-progress
            --exclude-mail
            './**/*.md'
      - name: Find Link Checker Issue
        id: link-checker-issue
        uses: micalevisk/last-issue-action@0d40124cc99ac8601c2516007f0c98ef3d27537b # v2.3.0
        with:
          state: open
          labels: |
            broken-links
      - name: Update Issue
        uses: peter-evans/create-issue-from-file@433e51abf769039ee20ba1293a088ca19d573b7f # renovate: tag=v4.0.1
        with:
          title: Broken links detected 🔗
          issue-number: "${{ steps.link-checker-issue.outputs.issue-number }}"
          content-filepath: ./lychee/out.md
          token: "${{ secrets.GITHUB_TOKEN }}"
          labels: |
            broken-links
